[package]
name = "harf"
description = "A HTTP watchdog"
version = "0.2.0"
authors = ["LeoTindall <lfstindall@gmail.com>"]
license = "MPL-2.0"

[dependencies]
serde = "1"
serde_derive = "1"
serde_json = "1"

hyper = "0.11"
futures = "0.1"
tokio-core = "0.1"

